version: '3.9'

services:
   db:
     ports:
       - 5432:5432
     container_name: postgres_container
     image: postgres
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: app
     restart: always
   migration:
     build: .
     container_name: webapp_db_migration_container
     ports:
       - 8083:8083
     environment:
       DB_URL: jdbc:postgresql://db:5432/app
       DB_USERNAME: postgres
       DB_PASSWORD: postgres
     depends_on:
       - db
     restart: always


